### PR TITLE
DSK-Image.py : Added compatibility with Linux and Windows in addition to OSX.

### PR DESCRIPTION
**Pull request by xandark**
Added ability for Linux and Windows to run this script. Now everyone can use this!
Added friendly and instructive error message for when pypng is not installed.
Fixed bugs that prevented the proper printing output.
Fixed the try/except/finally's to be try/except's.
Fixed inconsistent space and tab indentation which will fail with Python 3.
Fixed sys.exit(0) to exit with code of 1, which indicates an error to the shell.
Added the shebang to the first line so that the script can be run on its own.
Fixed the ImageMagick command line to be more compatible running under Windows shell.

### CODE REVIEW

**Comment by option8** [comment]
@xandark I've just updated several things in the script based on your earlier emails, as well as some places i want to add functions later. can you take a look at the latest?

i'm still working to get the hang of merging branches with git, and i appreciate your additions. i'm trying not to clobber your changes.

**Comment by xandark** [comment]
Hey Charles! Oh, you updated those things? Looks like we both did then :/  

To be honest, this is my foray into git, so I'm learning how to handle the git way of doing things, so I'll give it a go and get back to you.

**Comment by xandark** [comment]
Okay, looking at the addition to your code:

```python
try:
	subprocess.call(['convert', 'DiskImageTEMP.png', '-matte', '-virtual-pixel', 'transparent', '-resize', '1024x1024!', '-rotate', '90', '-distort', 'Polar', '512 110 512,512 -180,180', OUTPUTFILE])
except OSError:
    print("\n\nOops. This script requires ImageMagick: http://www.imagemagick.org/")
    sys.exit(0)
	
subprocess.call(['open', OUTPUTFILE])
```

... I see that you're using subprocess now, which is more modern, yet it also a lot of extra work. As it was before, the simple os.system() call works on all platforms as you originally coded it. All I did in the convert command line was change the " to ' for the polar coordinates, which is needed by the Windows command line, and works elsewhere too.

**Comment by option8** [comment]
The change to subprocess let's me check for more success/failure exit
codes, as well as making it easier to pass imagemagick variables as
arguments instead of concatenated strings. When I get around to 400/800k
disks, this will be important, since the size of image will vary.

Charles Mangin
Option8, LLC - Making Macs happy since 1999.
option8@option8.com | http://www.option8consulting.com
mobile: 919.368.7167

**Pull request merged**
